### ISSUE TITLE
请问什么时候可以开源 

### ISSUE THREAD

**Issue by Double-zh** [wwsource/SceneTracker#1]

**Comment by wwsource** [comment]
Thank you for noticing our work!🥰
We are accelerating the process of organizing the code. The release of the code is scheduled for June. If circumstances allow, it may be released sooner. Stay tuned!

**Comment by confSmiPaper4** [comment]
June has passed！

**Comment by zhouyelihua** [comment]
June is passed

**Comment by wwsource** [comment]
@Double-zh @zhouyelihua
Thank you all for your patience and understanding. The training and testing code is released! I hope it can be helpful for your work. If you have any queries, please don't hesitate to contact me~
