### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by luminousking** [wwsource/SceneTracker#3]
Hi, I encountered the follow issue when downloading dataset: 
```
<I> [20:25:45] LSFOdyssey.tar.gz <- /apps/bypy/LSFOdyssey.tar.gz
<I> [20:25:47] Local and remote file size DOESN'T match
[===_________________] 18% (40.6GB/219.2GB)  <E> [20:25:53] Waiting 10 seconds before retrying...
<E> [20:26:03] Request Try #2 / 5
<E> [20:26:05] Waiting 20 seconds before retrying...
<E> [20:26:25] Request Try #3 / 5
<E> [20:26:26] Waiting 30 seconds before retrying...
<E> [20:26:56] Request Try #4 / 5
<E> [20:26:58] Waiting 40 seconds before retrying...
<E> [20:27:38] Request Try #5 / 5
<E> [20:28:40] Maximum number (5) of tries failed.
<E> [20:28:40] ----------------------------------------------------------------
Error 140: Maximum retries reached
```
Then I tried to resume downloading but not working. However I successfully download the model ckpt via `bypy`. I checked several posts about solving this issue but none of them works. Are there any possible solutions to this issue? Or could you upload the dataset to Google Drive/Azure? 

Thank you so much for your help! :)

**Comment by wwsource** [comment]
Hi, you can use Baidu Netdisk to download. We are also trying other cloud storage, but it will take some time.

**Comment by wwsource** [comment]
@luminousking 
Hi, we upload the dataset to Huggingface. You can download it through the link [https://huggingface.co/datasets/wwcreator/LSFOdyssey](https://huggingface.co/datasets/wwcreator/LSFOdyssey). I hope it can be helpful for your work.
