### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by lxin98** [wwsource/SceneTracker#5]

**Comment by wwsource** [comment]
Thank you for noticing our work! We are trying to upload LSFOdyssey to Huggingface. Please wait for a while.

**Comment by wwsource** [comment]
@lxin98 
Hi, we upload the dataset to Huggingface. You can download it through the link [https://huggingface.co/datasets/wwcreator/LSFOdyssey](https://huggingface.co/datasets/wwcreator/LSFOdyssey). I hope it can be helpful for your work.

**Comment by lxin98** [comment]
@wwsource thanks very much！
