### ISSUE TITLE
Pretrained ckpt

### ISSUE THREAD

**Issue by ngoductuanlhp** [wwsource/SceneTracker#6]
Hi @wwsource,

Thank you for your great work. I want to run the demo with your provided ckpt. However, I cannot download it through the Baidu link. Could you instead upload your pretrained ckpt to GoogleDrive/HuggingFace?

Thank you!

**Comment by wwsource** [comment]
Thank you for noticing our work!
The trained weights are uploaded to Huggingface. You can download it through the link [https://huggingface.co/wwcreator/SceneTracker](https://huggingface.co/wwcreator/SceneTracker).
I hope it can be helpful for your work~

**Comment by ngoductuanlhp** [comment]
Great! Thank you.
