### ISSUE TITLE
How to download LSFDriving data

### ISSUE THREAD

**Issue by huanggan52** [wwsource/SceneTracker#9]
I am currently trying to access the LSFDriving data, but I couldn't find the download link anywhere. Could you please let me know if the dataset has been released? If so, could you provide the link or guidance on how to access it?

**Comment by wwsource** [comment]
Thank you for noticing our work!
At present, LSFDriving will not be released until our paper is accepted. Once there is any latest progress in the review, we will inform you immediately. You can use LSFOdyssey we have provided to train and test your methods. Thank you for your understanding~

**Comment by huanggan52** [comment]
Thank you for your response! I understand the situation, and I will start by using the LSFOdyssey dataset for training and testing my methods. I appreciate your efforts and look forward to any updates regarding LSFDriving. Thanks again!
